override github workflows with upstream contents

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,39 +3,30 @@ on:
   workflow_dispatch:
 
 jobs:
+  required-jobs:
+    uses: ./.github/workflows/build-common.yml
 
-  test-java8:
-    uses: ./.github/workflows/reusable-test-8.yml
+  # test-latest-deps is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central
+  # it can fail due to test code incompatibility with the new library version,
+  # or due to slight changes in emitted telemetry
 
-  test-java11:
-    uses: ./.github/workflows/reusable-test-11.yml
-
-  #   test-latest-deps is intentionally not included in the release workflows
-  #   because any time a new library version is released to maven central
-  #   it can fail due to test code incompatibility with the new library version,
-  #   or due to slight changes in emitted telemetry
-
-#  smoke-test:
-#    uses: ./.github/workflows/reusable-smoke-test.yml
-#
-  #   muzzle is intentionally not included in the release workflows
-  #   because any time a new library version is released to maven central it can fail,
-  #   and this is not a reason to hold up the release
-
-#  gradle-plugins:
-#    uses: ./.github/workflows/reusable-gradle-plugins.yml
-
+  # muzzle is intentionally not included in the release workflows
+  # because any time a new library version is released to maven central it can fail,
+  # and this is not a reason to hold up the release
 
   release:
+    runs-on: ubuntu-latest
     needs:
-      - test-java8
-      - test-java11
-#      - smoke-test
-#      - gradle-plugins
+      - required-jobs
     outputs:
       version: ${{ steps.create-github-release.outputs.version }}
-    runs-on: ubuntu-latest
     steps:
+      - run: |
+          if [[ $GITHUB_REF_NAME != release/* ]]; then
+            echo this workflow should only be run against release branches
+            exit 1
+          fi
 
       - uses: actions/checkout@v3
 
@@ -70,6 +61,16 @@ jobs:
         with:
           ref: main
 
+      - name: Check that change log update was merged to main
+        run: |
+          if [[ $VERSION == *.0 ]]; then
+            # not making a patch release
+            if ! grep --quiet "^## Version $VERSION " CHANGELOG.md; then
+              echo the pull request generated by prepare-release-branch.yml needs to be merged first
+              exit 1
+            fi
+          fi
+
         # back to the release branch
       - uses: actions/checkout@v3
         with:
@@ -81,21 +82,154 @@ jobs:
           distribution: temurin
           java-version: 17
 
-      - name: Setup Gradle
+      - name: Build and publish artifacts
         uses: gradle/gradle-build-action@v2
+        with:
+          arguments: assemble publishToSonatype closeAndReleaseSonatypeStagingRepository
+        env:
+          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
+          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
 
-      - name: Execute Gradle build
-        run: ./gradlew build -x :instrumentation:finatra-2.9:javaagent:test -x :instrumentation:hibernate:hibernate-4.0:javaagent:compileLatestDepTestJava -x :instrumentation:hibernate:hibernate-4.0:javaagent:compileLatestDepTestGroovy -x :instrumentation:play:play-mvc:play-mvc-2.6:javaagent:test
+      - name: Build and publish gradle plugins
+        uses: gradle/gradle-build-action@v2
+        env:
+          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
+          SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
+          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
+          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
+        with:
+          # Don't use publishToSonatype since we don't want to publish the marker artifact
+          arguments: build publishPlugins publishPluginMavenPublicationToSonatypeRepository closeAndReleaseSonatypeStagingRepository
+          build-root-directory: gradle-plugins
+
+      - name: Generate release notes
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # conditional blocks not indented because of the heredoc
+          if [[ $VERSION == *.0 ]]; then
+          cat > /tmp/release-notes.txt << EOF
+          This release targets the OpenTelemetry SDK $VERSION.
+
+          Note that many artifacts have the \`-alpha\` suffix attached to their version number, reflecting that they are still alpha quality and will continue to have breaking changes. Please see the [VERSIONING.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/VERSIONING.md#opentelemetry-java-instrumentation-versioning) for more details.
+
+          EOF
+          else
+          cat > /tmp/release-notes.txt << EOF
+          This is a patch release on the previous $PRIOR_VERSION release, fixing the issue(s) below.
+
+          EOF
+          fi
+
+          # CHANGELOG_SECTION.md is also used at the end of the release workflow
+          # for copying the change log updates to main
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            > /tmp/CHANGELOG_SECTION.md
+
+          # the complex perl regex is needed because markdown docs render newlines as soft wraps
+          # while release notes render them as line breaks
+          perl -0pe 's/(?<!\n)\n *(?!\n)(?![-*] )(?![1-9]+\. )/ /g' /tmp/CHANGELOG_SECTION.md \
+            >> /tmp/release-notes.txt
+
+          # conditional block not indented because of the heredoc
+          if [[ $VERSION == *.0 ]]; then
+          cat >> /tmp/release-notes.txt << EOF
+          ### 🙇 Thank you
+
+          This release was possible thanks to the following contributors who shared their brilliant ideas and awesome pull requests:
+
+          EOF
+
+          .github/scripts/generate-release-contributors.sh v$PRIOR_VERSION >> /tmp/release-notes.txt
+          fi
 
       - id: create-github-release
         name: Create GitHub release
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           cp javaagent/build/libs/opentelemetry-javaagent-${VERSION}.jar opentelemetry-javaagent.jar
           gh release create --target $GITHUB_REF_NAME \
                             --title "Version $VERSION" \
+                            --notes-file /tmp/release-notes.txt \
+                            --discussion-category announcements \
                             v$VERSION \
                             opentelemetry-javaagent.jar
 
-          echo "::set-output name=version::$VERSION"
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
+
+  merge-change-log-to-main:
+    runs-on: ubuntu-latest
+    needs:
+      - release
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Copy change log section from release branch
+        env:
+          VERSION: ${{ needs.release.outputs.version }}
+        run: |
+          sed -n "0,/^## Version $VERSION /d;/^## Version /q;p" CHANGELOG.md \
+            > /tmp/changelog-section.md
+
+      - uses: actions/checkout@v3
+        with:
+          ref: main
+
+      - name: Merge change log to main
+        env:
+          VERSION: ${{ needs.release.outputs.version }}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          release_date=$(gh release view v$VERSION --json publishedAt --jq .publishedAt | sed 's/T.*//')
+          RELEASE_DATE=$release_date .github/scripts/merge-change-log-after-release.sh
+
+      - name: Use CLA approved github bot
+        run: .github/scripts/use-cla-approved-github-bot.sh
+
+      - name: Create pull request against main
+        env:
+          VERSION: ${{ needs.release.outputs.version }}
+          # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          if git diff --quiet; then
+            if [[ $VERSION == *.0 ]]; then
+              echo there are no updates to merge, not creating pull request
+              exit 0 # success
+            else
+              echo patch release notes did not get applied for some reason
+              exit 1 # failure
+            fi
+          fi
+
+          message="Merge change log updates from $GITHUB_REF_NAME"
+          body="Merge log updates from \`$GITHUB_REF_NAME\`."
+          branch="opentelemetrybot/merge-change-log-updates-from-${GITHUB_REF_NAME//\//-}"
+
+          git checkout -b $branch
+          git commit -a -m "$message"
+          git push --set-upstream origin $branch
+          gh pr create --title "$message" \
+                       --body "$body" \
+                       --base main
+
+  create-operator-pull-request:
+    needs: release
+    uses: ./.github/workflows/reusable-create-operator-pull-request.yml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
+
+  create-website-pull-request:
+    needs: release
+    uses: ./.github/workflows/reusable-create-website-pull-request.yml
+    with:
+      version: ${{ needs.release.outputs.version }}
+    secrets:
+      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
